using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using ServiceReference1;
public partial class _Default : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {
        string strRet;

        //create object for parameters
        ServiceReference1.SAP_Cols scols = new SAP_Cols();

        //create service object
        ServiceReference1.ServiceClient sc = new ServiceClient(); 
        
        //fill up values of parameters

        scols.tariftyp = "0";
        scols.circle = "1";
        scols.division = "2";
        scols.sub_div = "3";
        scols.bill_cycle = "4";
        scols.zz_year = "5";
        scols.bill_date = "6";
        scols.opbel = "7";
        scols.faedn_cash = "8";
        scols.faedn_cheque = "9";
        scols.nft_admvlt = "10";
        scols.nft_supvlt = "11";
        scols.nft_mtrvlt = "12";
        scols.vkont = "13";
        scols.vkona = "14";
        scols.name = "15";
        scols.address = "16";
        scols.date_of_conn = "17";
        scols.sndgen = "18";
        scols.sndif = "19";
        scols.sndpiu = "20";
        scols.sndsea = "21";
        scols.sndgen_date = "22";
        scols.sndif_date = "23";
        scols.sndpiu_date = "24";
        scols.sndsea_date = "25";
        scols.cdgen = "26";
        scols.cdif = "27";
        scols.cdpiu = "28";
        scols.cdsea = "29";
        scols.cdgen_date = "30";
        scols.cdif_date = "31";
        scols.cdpiu_date = "32";
        scols.cdsea_date = "33";
        scols.ind_typ = "34";
        scols.mmc = "35";
        scols.sea_on_date = "36";
        scols.sea_off_date = "37";
        scols.peak_load = "38";
        scols.peak_load_s_date = "39";
        scols.peak_load_e_date = "40";
        scols.pre_read_date = "41";
        scols.cur_read_date = "42";
        scols.no_days_bill = "43";
        scols.meter_owner = "44";
        scols.mco_date = "45";
        scols.ctpt = "46";
        scols.sjo_date = "47";
        scols.feeder_code = "48";
        scols.feeder_name = "49";
        scols.mtr_security_amt = "50";
        scols.adv_cons_deposit = "51";
        scols.metetr_read_note = "52";
        scols.pre_met_red_kwh = "53";
        scols.pre_met_red_kvah = "54";
        scols.pre_met_red_kva = "55";
        scols.curr_met_red_kwh = "56";
        scols.curr_met_red_kvah = "57";
        scols.curr_met_red_kva = "58";
        scols.mtr_multiplier = "59";
        scols.line_ctr = "60";
        scols.mtr_ratio = "61";
        scols.mtr_volt_ratio = "62";
        scols.overall_multiplier = "63";
        scols.mmts_corr = "64";
        scols.add_sup_unit_kwh = "65";
        scols.add_sup_unit_kvah = "66";
        scols.add_sup_unit_kva = "67";
        scols.cur_cons_kwh = "68";
        scols.cur_cons_kvah = "69";
        scols.cur_cons_kva = "70";
        scols.old_pre_met_kwh = "71";
        scols.old_pre_met_kvah = "72";
        scols.old_pre_met_kva = "73";
        scols.old_curr_met_kwh = "74";
        scols.old_curr_met_kvah = "75";
        scols.old_curr_met_kva = "76";
        scols.old_mtr_multiplier = "77";
        scols.old_line_ctr = "78";
        scols.old_mtr_ratio = "79";
        scols.old_mtr_volt_ratio = "80";
        scols.old_all_multiplier = "81";
        scols.old_mmts_corr = "82";
        scols.old_add_sup_kwh = "83";
        scols.old_add_sup_kvah = "84";
        scols.old_add_sup_kva = "85";
        scols.old_cons_kwh = "86";
        scols.old_cons_kvah = "87";
        scols.old_cons_kva = "88";
        scols.tot_cons_kwh = "89";
        scols.tot_cons_kvah = "90";
        scols.tot_cons_kva = "91";
        scols.pf = "92";
        scols.be_code = "93";
        scols.concess_cons = "94";
        scols.ec = "95";
        scols.mmc_add = "96";
        scols.pf_int_sur = "97";
        scols.ht_rbt = "98";
        scols.fca = "99";
        scols.dmnd_schr = "100";
        scols.plec = "101";
        scols.volt_schr = "102";
        scols.fix_chrg = "103";
        scols.ot_chrg = "104";
        scols.violation_chrg = "105";
        scols.sop = "106";
        scols.mtr_rent = "107";
        scols.mcb_rent = "108";
        scols.ser_rent = "109";
        scols.ser_chrg = "110";
        scols.tot_rentals = "111";
        scols.pre_round = "112";
        scols.curr_round = "113";
        scols.curr_sop = "114";
        scols.curr_rental = "115";
        scols.curr_ed = "116";
        scols.curr_oct = "117";
        scols.curr_misc = "118";
        scols.curr_total = "119";
        scols.adj_sop = "120";
        scols.adj_rental = "121";
        scols.adj_ed = "122";
        scols.adj_oct = "123";
        scols.adj_misc = "124";
        scols.adj_total = "125";
        scols.snd_chrg_sop = "126";
        scols.snd_chrg_rental = "127";
        scols.snd_chrg_ed = "128";
        scols.snd_chrg_oct = "129";
        scols.snd_chrg_misc = "130";
        scols.snd_chrg_total = "131";
        scols.snd_allw_sop = "132";
        scols.snd_allw_rental = "133";
        scols.snd_allw_ed = "134";
        scols.snd_allw_oct = "135";
        scols.snd_allw_misc = "136";
        scols.snd_allw_total = "137";
        scols.arr_pre_sop = "138";
        scols.arr_pre_rental = "139";
        scols.arr_pre_ed = "140";
        scols.arr_pre_oct = "141";
        scols.arr_pre_misc = "142";
        scols.arr_pre_total = "143";
        scols.arr_curr_sop = "144";
        scols.arr_curr_rental = "145";
        scols.arr_curr_ed = "146";
        scols.arr_curr_oct = "147";
        scols.arr_curr_misc = "148";
        scols.arr_curr_total = "149";
        scols.net_sop = "150";
        scols.net_rental = "151";
        scols.net_ed = "152";
        scols.net_oct = "153";
        scols.net_misc = "154";
        scols.net_tot = "155";
        scols.net_payable = "156";
        scols.lpsc_amnt_2 = "157";
        scols.lpcs_amnt_5 = "158";
        scols.amt_aft_due_dat_2 = "159";
        scols.amt_aft_due_dat_5 = "160";
        scols.cons_kwh_1 = "161";
        scols.cons_kvah_1 = "162";
        scols.cons_kva_1 = "163";
        scols.cons_kwh_2 = "164";
        scols.cons_kvah_2 = "165";
        scols.cons_kva_2 = "166";
        scols.cons_kwh_3 = "167";
        scols.cons_kvah_3 = "168";
        scols.cons_kva_3 = "169";
        scols.cons_kwh_4 = "170";
        scols.cons_kvah_4 = "171";
        scols.cons_kva_4 = "172";
        scols.cons_kwh_5 = "173";
        scols.cons_kvah_5 = "174";
        scols.cons_kva_5 = "175";
        scols.cons_kwh_6 = "176";
        scols.cons_kvah_6 = "177";
        scols.cons_kva_6 = "178";
        scols.cons_kwh_7 = "179";
        scols.cons_kvah_7 = "180";
        scols.cons_kva_7 = "181";
        scols.cons_kwh_8 = "182";
        scols.cons_kvah_8 = "183";
        scols.cons_kva_8 = "184";
        scols.cons_kwh_9 = "185";
        scols.cons_kvah_9 = "186";
        scols.cons_kva_9 = "187";
        scols.cons_kwh_10 = "188";
        scols.cons_kvah_10 = "189";
        scols.cons_kva_10 = "190";
        scols.cons_kwh_11 = "191";
        scols.cons_kvah_11 = "192";
        scols.cons_kva_11 = "193";
        scols.cons_kwh_12 = "194";
        scols.cons_kvah_12 = "195";
        scols.cons_kva_12 = "196";
        scols.cons_kwh_13 = "197";
        scols.cons_kvah_13 = "198";
        scols.cons_kva_13 = "199";
        scols.cons_kwh_14 = "200";
        scols.cons_kvah_14 = "201";
        scols.cons_kva_14 = "202";
        scols.cons_kwh_15 = "203";
        scols.cons_kvah_15 = "204";
        scols.cons_kva_15 = "205";
        scols.cons_kwh_16 = "206";
        scols.cons_kvah_16 = "207";
        scols.cons_kva_16 = "208";
        scols.cons_kwh_17 = "209";
        scols.cons_kvah_17 = "210";
        scols.cons_kva_17 = "211";
        scols.cons_kwh_18 = "212";
        scols.cons_kvah_18 = "213";
        scols.cons_kva_18 = "214";
        scols.cons_kwh_19 = "215";
        scols.cons_kvah_19 = "216";
        scols.cons_kva_19 = "217";
        scols.cons_kwh_20 = "218";
        scols.cons_kvah_20 = "219";
        scols.cons_kva_20 = "220";
        scols.cons_kwh_21 = "221";
        scols.cons_kvah_21 = "222";
        scols.cons_kva_21 = "223";
        scols.cons_kwh_22 = "224";
        scols.cons_kvah_22 = "225";
        scols.cons_kva_22 = "226";
        scols.cons_kwh_23 = "227";
        scols.cons_kvah_23 = "228";
        scols.cons_kva_23 = "229";
        scols.cons_kwh_24 = "230";
        scols.cons_kvah_24 = "231";
        scols.cons_kva_24 = "232";
        scols.variation = "233";
        scols.tod_schr_cons = "234";
        scols.tod_schr_amt = "235";
        scols.tod_rbt_cons = "236";
        scols.tod_rbt_amt = "237";


        
        //call service and check the returned value
        strRet = sc.GetDataUsingDataContract(scols);

        //close the service client
        sc.Close();
    }
}