//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="MI_PostPayment_OB_SYNCBinding", Namespace="http://pspcl.com/xi/WS/IF0004_PostPayment_100")]
public partial class SAP_Payment_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback MI_PostPayment_OB_SYNCOperationCompleted;
    
    /// <remarks/>
    public SAP_Payment_Service() {
        this.Url = "http://sapdevpi1:50200/XISOAPAdapter/MessageServlet?senderParty=&senderService=WS" +
            "_DV&receiverParty=&receiverService=&interface=MI_PostPayment_OB_SYNC&interfaceNa" +
            "mespace=http%3A%2F%2Fpspcl.com%2Fxi%2FWS%2FIF0004_PostPayment_100";
    }
    
    /// <remarks/>
    public event MI_PostPayment_OB_SYNCCompletedEventHandler MI_PostPayment_OB_SYNCCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlArrayAttribute("MT_PostPayment_Res", Namespace="http://pspcl.com/xi/WS/IF0004_PostPayment_100")]
    [return: System.Xml.Serialization.XmlArrayItemAttribute("PAYMENT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public DT_PostPayment_ResPAYMENT[] MI_PostPayment_OB_SYNC([System.Xml.Serialization.XmlArrayAttribute(Namespace="http://pspcl.com/xi/WS/IF0004_PostPayment_100")] [System.Xml.Serialization.XmlArrayItemAttribute("Payment", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] DT_PostPayment_ReqPayment[] MT_PostPayment_Req) {
        object[] results = this.Invoke("MI_PostPayment_OB_SYNC", new object[] {
                    MT_PostPayment_Req});
        return ((DT_PostPayment_ResPAYMENT[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginMI_PostPayment_OB_SYNC(DT_PostPayment_ReqPayment[] MT_PostPayment_Req, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("MI_PostPayment_OB_SYNC", new object[] {
                    MT_PostPayment_Req}, callback, asyncState);
    }
    
    /// <remarks/>
    public DT_PostPayment_ResPAYMENT[] EndMI_PostPayment_OB_SYNC(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((DT_PostPayment_ResPAYMENT[])(results[0]));
    }
    
    /// <remarks/>
    public void MI_PostPayment_OB_SYNCAsync(DT_PostPayment_ReqPayment[] MT_PostPayment_Req) {
        this.MI_PostPayment_OB_SYNCAsync(MT_PostPayment_Req, null);
    }
    
    /// <remarks/>
    public void MI_PostPayment_OB_SYNCAsync(DT_PostPayment_ReqPayment[] MT_PostPayment_Req, object userState) {
        if ((this.MI_PostPayment_OB_SYNCOperationCompleted == null)) {
            this.MI_PostPayment_OB_SYNCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMI_PostPayment_OB_SYNCOperationCompleted);
        }
        this.InvokeAsync("MI_PostPayment_OB_SYNC", new object[] {
                    MT_PostPayment_Req}, this.MI_PostPayment_OB_SYNCOperationCompleted, userState);
    }
    
    private void OnMI_PostPayment_OB_SYNCOperationCompleted(object arg) {
        if ((this.MI_PostPayment_OB_SYNCCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.MI_PostPayment_OB_SYNCCompleted(this, new MI_PostPayment_OB_SYNCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pspcl.com/xi/WS/IF0004_PostPayment_100")]
public partial class DT_PostPayment_ReqPayment {
    
    private string tRANSACTION_IDField;
    
    private string sOURCE_CODEField;
    
    private string aGENCY_CODEField;
    
    private string cONTRACT_ACCOUNTField;
    
    private string pAYMENT_AMOUNTField;
    
    private System.DateTime dOCUMENT_DATEField;
    
    private bool dOCUMENT_DATEFieldSpecified;
    
    private System.DateTime pOSTING_DATEField;
    
    private System.DateTime vALUE_DATEField;
    
    private string dOCUMENT_NUMBERField;
    
    private string pAYMENT_MODEField;
    
    private string bRANCHField;
    
    private string cASHDESKField;
    
    private string cHEQUE_NOField;
    
    private System.DateTime cHEQUE_DATEField;
    
    private bool cHEQUE_DATEFieldSpecified;
    
    private string mICRCODEField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TRANSACTION_ID {
        get {
            return this.tRANSACTION_IDField;
        }
        set {
            this.tRANSACTION_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SOURCE_CODE {
        get {
            return this.sOURCE_CODEField;
        }
        set {
            this.sOURCE_CODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AGENCY_CODE {
        get {
            return this.aGENCY_CODEField;
        }
        set {
            this.aGENCY_CODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CONTRACT_ACCOUNT {
        get {
            return this.cONTRACT_ACCOUNTField;
        }
        set {
            this.cONTRACT_ACCOUNTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PAYMENT_AMOUNT {
        get {
            return this.pAYMENT_AMOUNTField;
        }
        set {
            this.pAYMENT_AMOUNTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
    public System.DateTime DOCUMENT_DATE {
        get {
            return this.dOCUMENT_DATEField;
        }
        set {
            this.dOCUMENT_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DOCUMENT_DATESpecified {
        get {
            return this.dOCUMENT_DATEFieldSpecified;
        }
        set {
            this.dOCUMENT_DATEFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
    public System.DateTime POSTING_DATE {
        get {
            return this.pOSTING_DATEField;
        }
        set {
            this.pOSTING_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
    public System.DateTime VALUE_DATE {
        get {
            return this.vALUE_DATEField;
        }
        set {
            this.vALUE_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DOCUMENT_NUMBER {
        get {
            return this.dOCUMENT_NUMBERField;
        }
        set {
            this.dOCUMENT_NUMBERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PAYMENT_MODE {
        get {
            return this.pAYMENT_MODEField;
        }
        set {
            this.pAYMENT_MODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BRANCH {
        get {
            return this.bRANCHField;
        }
        set {
            this.bRANCHField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CASHDESK {
        get {
            return this.cASHDESKField;
        }
        set {
            this.cASHDESKField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CHEQUE_NO {
        get {
            return this.cHEQUE_NOField;
        }
        set {
            this.cHEQUE_NOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
    public System.DateTime CHEQUE_DATE {
        get {
            return this.cHEQUE_DATEField;
        }
        set {
            this.cHEQUE_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CHEQUE_DATESpecified {
        get {
            return this.cHEQUE_DATEFieldSpecified;
        }
        set {
            this.cHEQUE_DATEFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MICRCODE {
        get {
            return this.mICRCODEField;
        }
        set {
            this.mICRCODEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pspcl.com/xi/WS/IF0004_PostPayment_100")]
public partial class DT_PostPayment_ResPAYMENT {
    
    private string tRANSACTION_IDField;
    
    private string pAYMENT_DOC_NUMBField;
    
    private string messageIDField;
    
    private string errorCodeField;
    
    private string errorDescrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TRANSACTION_ID {
        get {
            return this.tRANSACTION_IDField;
        }
        set {
            this.tRANSACTION_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PAYMENT_DOC_NUMB {
        get {
            return this.pAYMENT_DOC_NUMBField;
        }
        set {
            this.pAYMENT_DOC_NUMBField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MessageID {
        get {
            return this.messageIDField;
        }
        set {
            this.messageIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ErrorCode {
        get {
            return this.errorCodeField;
        }
        set {
            this.errorCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ErrorDescr {
        get {
            return this.errorDescrField;
        }
        set {
            this.errorDescrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void MI_PostPayment_OB_SYNCCompletedEventHandler(object sender, MI_PostPayment_OB_SYNCCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class MI_PostPayment_OB_SYNCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal MI_PostPayment_OB_SYNCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public DT_PostPayment_ResPAYMENT[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((DT_PostPayment_ResPAYMENT[])(this.results[0]));
        }
    }
}
