//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://pspcl.com/xi/WS/IF0004_PostPayment_100", ConfigurationName="MI_PostPayment_OB_SYNC")]
public interface MI_PostPayment_OB_SYNC
{
    
    // CODEGEN: Generating message contract since the operation MI_PostPayment_OB_SYNC is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    MI_PostPayment_OB_SYNCResponse MI_PostPayment_OB_SYNC(MI_PostPayment_OB_SYNCRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pspcl.com/xi/WS/IF0004_PostPayment_100")]
public partial class DT_PostPayment_ReqPayment
{
    
    private string tRANSACTION_IDField;
    
    private string sOURCE_CODEField;
    
    private string aGENCY_CODEField;
    
    private string cONTRACT_ACCOUNTField;
    
    private string pAYMENT_AMOUNTField;
    
    private System.DateTime dOCUMENT_DATEField;
    
    private bool dOCUMENT_DATEFieldSpecified;
    
    private System.DateTime pOSTING_DATEField;
    
    private System.DateTime vALUE_DATEField;
    
    private string dOCUMENT_NUMBERField;
    
    private string pAYMENT_MODEField;
    
    private string bRANCHField;
    
    private string cASHDESKField;
    
    private string cHEQUE_NOField;
    
    private System.DateTime cHEQUE_DATEField;
    
    private bool cHEQUE_DATEFieldSpecified;
    
    private string mICRCODEField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string TRANSACTION_ID
    {
        get
        {
            return this.tRANSACTION_IDField;
        }
        set
        {
            this.tRANSACTION_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string SOURCE_CODE
    {
        get
        {
            return this.sOURCE_CODEField;
        }
        set
        {
            this.sOURCE_CODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string AGENCY_CODE
    {
        get
        {
            return this.aGENCY_CODEField;
        }
        set
        {
            this.aGENCY_CODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string CONTRACT_ACCOUNT
    {
        get
        {
            return this.cONTRACT_ACCOUNTField;
        }
        set
        {
            this.cONTRACT_ACCOUNTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string PAYMENT_AMOUNT
    {
        get
        {
            return this.pAYMENT_AMOUNTField;
        }
        set
        {
            this.pAYMENT_AMOUNTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=5)]
    public System.DateTime DOCUMENT_DATE
    {
        get
        {
            return this.dOCUMENT_DATEField;
        }
        set
        {
            this.dOCUMENT_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DOCUMENT_DATESpecified
    {
        get
        {
            return this.dOCUMENT_DATEFieldSpecified;
        }
        set
        {
            this.dOCUMENT_DATEFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=6)]
    public System.DateTime POSTING_DATE
    {
        get
        {
            return this.pOSTING_DATEField;
        }
        set
        {
            this.pOSTING_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=7)]
    public System.DateTime VALUE_DATE
    {
        get
        {
            return this.vALUE_DATEField;
        }
        set
        {
            this.vALUE_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
    public string DOCUMENT_NUMBER
    {
        get
        {
            return this.dOCUMENT_NUMBERField;
        }
        set
        {
            this.dOCUMENT_NUMBERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
    public string PAYMENT_MODE
    {
        get
        {
            return this.pAYMENT_MODEField;
        }
        set
        {
            this.pAYMENT_MODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
    public string BRANCH
    {
        get
        {
            return this.bRANCHField;
        }
        set
        {
            this.bRANCHField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
    public string CASHDESK
    {
        get
        {
            return this.cASHDESKField;
        }
        set
        {
            this.cASHDESKField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
    public string CHEQUE_NO
    {
        get
        {
            return this.cHEQUE_NOField;
        }
        set
        {
            this.cHEQUE_NOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=13)]
    public System.DateTime CHEQUE_DATE
    {
        get
        {
            return this.cHEQUE_DATEField;
        }
        set
        {
            this.cHEQUE_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CHEQUE_DATESpecified
    {
        get
        {
            return this.cHEQUE_DATEFieldSpecified;
        }
        set
        {
            this.cHEQUE_DATEFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
    public string MICRCODE
    {
        get
        {
            return this.mICRCODEField;
        }
        set
        {
            this.mICRCODEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pspcl.com/xi/WS/IF0004_PostPayment_100")]
public partial class DT_PostPayment_ResPAYMENT
{
    
    private string tRANSACTION_IDField;
    
    private string pAYMENT_DOC_NUMBField;
    
    private string messageIDField;
    
    private string errorCodeField;
    
    private string errorDescrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string TRANSACTION_ID
    {
        get
        {
            return this.tRANSACTION_IDField;
        }
        set
        {
            this.tRANSACTION_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string PAYMENT_DOC_NUMB
    {
        get
        {
            return this.pAYMENT_DOC_NUMBField;
        }
        set
        {
            this.pAYMENT_DOC_NUMBField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string MessageID
    {
        get
        {
            return this.messageIDField;
        }
        set
        {
            this.messageIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string ErrorCode
    {
        get
        {
            return this.errorCodeField;
        }
        set
        {
            this.errorCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string ErrorDescr
    {
        get
        {
            return this.errorDescrField;
        }
        set
        {
            this.errorDescrField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class MI_PostPayment_OB_SYNCRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pspcl.com/xi/WS/IF0004_PostPayment_100", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Payment", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public DT_PostPayment_ReqPayment[] MT_PostPayment_Req;
    
    public MI_PostPayment_OB_SYNCRequest()
    {
    }
    
    public MI_PostPayment_OB_SYNCRequest(DT_PostPayment_ReqPayment[] MT_PostPayment_Req)
    {
        this.MT_PostPayment_Req = MT_PostPayment_Req;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class MI_PostPayment_OB_SYNCResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pspcl.com/xi/WS/IF0004_PostPayment_100", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("PAYMENT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public DT_PostPayment_ResPAYMENT[] MT_PostPayment_Res;
    
    public MI_PostPayment_OB_SYNCResponse()
    {
    }
    
    public MI_PostPayment_OB_SYNCResponse(DT_PostPayment_ResPAYMENT[] MT_PostPayment_Res)
    {
        this.MT_PostPayment_Res = MT_PostPayment_Res;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface MI_PostPayment_OB_SYNCChannel : MI_PostPayment_OB_SYNC, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MI_PostPayment_OB_SYNCClient : System.ServiceModel.ClientBase<MI_PostPayment_OB_SYNC>, MI_PostPayment_OB_SYNC
{
    
    public MI_PostPayment_OB_SYNCClient()
    {
    }
    
    public MI_PostPayment_OB_SYNCClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MI_PostPayment_OB_SYNCClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MI_PostPayment_OB_SYNCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MI_PostPayment_OB_SYNCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    MI_PostPayment_OB_SYNCResponse MI_PostPayment_OB_SYNC.MI_PostPayment_OB_SYNC(MI_PostPayment_OB_SYNCRequest request)
    {
        return base.Channel.MI_PostPayment_OB_SYNC(request);
    }
    
    public DT_PostPayment_ResPAYMENT[] MI_PostPayment_OB_SYNC(DT_PostPayment_ReqPayment[] MT_PostPayment_Req)
    {
        MI_PostPayment_OB_SYNCRequest inValue = new MI_PostPayment_OB_SYNCRequest();
        inValue.MT_PostPayment_Req = MT_PostPayment_Req;
        MI_PostPayment_OB_SYNCResponse retVal = ((MI_PostPayment_OB_SYNC)(this)).MI_PostPayment_OB_SYNC(inValue);
        return retVal.MT_PostPayment_Res;
    }
}
