<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:tns="http://tempuri.org/" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Service_Rcv_SAP_Rec" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xs:schema elementFormDefault="qualified" targetNamespace="http://tempuri.org/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:import namespace="http://schemas.datacontract.org/2004/07/" />
      <xs:element name="GetDataUsingDataContract">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q1="http://schemas.datacontract.org/2004/07/" minOccurs="0" name="composite" nillable="true" type="q1:SAP_Cols" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetDataUsingDataContractResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="GetDataUsingDataContractResult" nillable="true" type="xs:string" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:schema>
    <xs:schema xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/" attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:element name="anyType" nillable="true" type="xs:anyType" />
      <xs:element name="anyURI" nillable="true" type="xs:anyURI" />
      <xs:element name="base64Binary" nillable="true" type="xs:base64Binary" />
      <xs:element name="boolean" nillable="true" type="xs:boolean" />
      <xs:element name="byte" nillable="true" type="xs:byte" />
      <xs:element name="dateTime" nillable="true" type="xs:dateTime" />
      <xs:element name="decimal" nillable="true" type="xs:decimal" />
      <xs:element name="double" nillable="true" type="xs:double" />
      <xs:element name="float" nillable="true" type="xs:float" />
      <xs:element name="int" nillable="true" type="xs:int" />
      <xs:element name="long" nillable="true" type="xs:long" />
      <xs:element name="QName" nillable="true" type="xs:QName" />
      <xs:element name="short" nillable="true" type="xs:short" />
      <xs:element name="string" nillable="true" type="xs:string" />
      <xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte" />
      <xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt" />
      <xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong" />
      <xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort" />
      <xs:element name="char" nillable="true" type="tns:char" />
      <xs:simpleType name="char">
        <xs:restriction base="xs:int" />
      </xs:simpleType>
      <xs:element name="duration" nillable="true" type="tns:duration" />
      <xs:simpleType name="duration">
        <xs:restriction base="xs:duration">
          <xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?" />
          <xs:minInclusive value="-P10675199DT2H48M5.4775808S" />
          <xs:maxInclusive value="P10675199DT2H48M5.4775807S" />
        </xs:restriction>
      </xs:simpleType>
      <xs:element name="guid" nillable="true" type="tns:guid" />
      <xs:simpleType name="guid">
        <xs:restriction base="xs:string">
          <xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}" />
        </xs:restriction>
      </xs:simpleType>
      <xs:attribute name="FactoryType" type="xs:QName" />
      <xs:attribute name="Id" type="xs:ID" />
      <xs:attribute name="Ref" type="xs:IDREF" />
    </xs:schema>
    <xs:schema xmlns:tns="http://schemas.datacontract.org/2004/07/" elementFormDefault="qualified" targetNamespace="http://schemas.datacontract.org/2004/07/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:complexType name="SAP_Cols">
        <xs:sequence>
          <xs:element minOccurs="0" name="add_sup_unit_kva" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="add_sup_unit_kvah" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="add_sup_unit_kwh" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="address" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="adj_ed" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="adj_misc" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="adj_oct" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="adj_rental" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="adj_sop" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="adj_total" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="adv_cons_deposit" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="amt_aft_due_dat_2" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="amt_aft_due_dat_5" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="arr_curr_ed" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="arr_curr_misc" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="arr_curr_oct" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="arr_curr_rental" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="arr_curr_sop" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="arr_curr_total" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="arr_pre_ed" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="arr_pre_misc" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="arr_pre_oct" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="arr_pre_rental" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="arr_pre_sop" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="arr_pre_total" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="be_code" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="bill_cycle" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="bill_date" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cdgen" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cdgen_date" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cdif" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cdif_date" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cdpiu" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cdpiu_date" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cdsea" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cdsea_date" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="circle" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="concess_cons" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kva_1" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kva_10" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kva_11" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kva_12" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kva_13" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kva_14" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kva_15" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kva_16" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kva_17" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kva_18" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kva_19" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kva_2" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kva_20" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kva_21" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kva_22" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kva_23" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kva_24" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kva_3" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kva_4" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kva_5" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kva_6" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kva_7" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kva_8" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kva_9" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kvah_1" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kvah_10" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kvah_11" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kvah_12" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kvah_13" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kvah_14" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kvah_15" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kvah_16" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kvah_17" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kvah_18" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kvah_19" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kvah_2" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kvah_20" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kvah_21" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kvah_22" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kvah_23" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kvah_24" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kvah_3" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kvah_4" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kvah_5" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kvah_6" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kvah_7" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kvah_8" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kvah_9" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kwh_1" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kwh_10" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kwh_11" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kwh_12" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kwh_13" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kwh_14" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kwh_15" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kwh_16" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kwh_17" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kwh_18" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kwh_19" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kwh_2" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kwh_20" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kwh_21" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kwh_22" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kwh_23" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kwh_24" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kwh_3" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kwh_4" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kwh_5" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kwh_6" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kwh_7" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kwh_8" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cons_kwh_9" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="ctpt" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cur_cons_kva" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cur_cons_kvah" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cur_cons_kwh" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cur_read_date" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="curr_ed" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="curr_met_red_kva" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="curr_met_red_kvah" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="curr_met_red_kwh" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="curr_misc" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="curr_oct" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="curr_rental" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="curr_round" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="curr_sop" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="curr_total" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="date_of_conn" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="division" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="dmnd_schr" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="ec" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="faedn_cash" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="faedn_cheque" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="fca" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="feeder_code" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="feeder_name" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="fix_chrg" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="ht_rbt" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="ind_typ" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="line_ctr" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="lpcs_amnt_5" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="lpsc_amnt_2" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="mcb_rent" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="mco_date" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="meter_owner" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="metetr_read_note" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="mmc" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="mmc_add" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="mmts_corr" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="mtr_multiplier" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="mtr_ratio" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="mtr_rent" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="mtr_security_amt" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="mtr_volt_ratio" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="name" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="net_ed" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="net_misc" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="net_oct" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="net_payable" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="net_rental" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="net_sop" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="net_tot" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="nft_admvlt" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="nft_mtrvlt" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="nft_supvlt" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="no_days_bill" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="old_add_sup_kva" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="old_add_sup_kvah" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="old_add_sup_kwh" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="old_all_multiplier" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="old_cons_kva" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="old_cons_kvah" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="old_cons_kwh" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="old_curr_met_kva" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="old_curr_met_kvah" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="old_curr_met_kwh" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="old_line_ctr" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="old_mmts_corr" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="old_mtr_multiplier" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="old_mtr_ratio" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="old_mtr_volt_ratio" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="old_pre_met_kva" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="old_pre_met_kvah" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="old_pre_met_kwh" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="opbel" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="ot_chrg" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="overall_multiplier" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="peak_load" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="peak_load_e_date" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="peak_load_s_date" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="pf" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="pf_int_sur" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="plec" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="pre_met_red_kva" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="pre_met_red_kvah" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="pre_met_red_kwh" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="pre_read_date" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="pre_round" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="sea_off_date" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="sea_on_date" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="ser_chrg" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="ser_rent" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="sjo_date" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="snd_allw_ed" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="snd_allw_misc" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="snd_allw_oct" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="snd_allw_rental" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="snd_allw_sop" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="snd_allw_total" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="snd_chrg_ed" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="snd_chrg_misc" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="snd_chrg_oct" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="snd_chrg_rental" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="snd_chrg_sop" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="snd_chrg_total" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="sndgen" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="sndgen_date" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="sndif" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="sndif_date" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="sndpiu" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="sndpiu_date" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="sndsea" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="sndsea_date" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="sop" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="sub_div" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="tariftyp" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="tod_rbt_amt" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="tod_rbt_cons" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="tod_schr_amt" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="tod_schr_cons" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="tot_cons_kva" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="tot_cons_kvah" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="tot_cons_kwh" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="tot_rentals" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="variation" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="violation_chrg" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="vkona" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="vkont" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="volt_schr" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="zz_year" nillable="true" type="xs:string" />
        </xs:sequence>
      </xs:complexType>
      <xs:element name="SAP_Cols" nillable="true" type="tns:SAP_Cols" />
    </xs:schema>
  </wsdl:types>
  <wsdl:message name="IService_GetDataUsingDataContract_InputMessage">
    <wsdl:part name="parameters" element="tns:GetDataUsingDataContract" />
  </wsdl:message>
  <wsdl:message name="IService_GetDataUsingDataContract_OutputMessage">
    <wsdl:part name="parameters" element="tns:GetDataUsingDataContractResponse" />
  </wsdl:message>
  <wsdl:portType name="IService">
    <wsdl:operation name="GetDataUsingDataContract">
      <wsdl:input wsaw:Action="http://tempuri.org/IService/GetDataUsingDataContract" message="tns:IService_GetDataUsingDataContract_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IService/GetDataUsingDataContractResponse" message="tns:IService_GetDataUsingDataContract_OutputMessage" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BasicHttpBinding_IService" type="tns:IService">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="GetDataUsingDataContract">
      <soap:operation soapAction="http://tempuri.org/IService/GetDataUsingDataContract" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Service_Rcv_SAP_Rec">
    <wsdl:port name="BasicHttpBinding_IService" binding="tns:BasicHttpBinding_IService">
      <soap:address location="http://localhost:1298/WCFService_RcvSAPBill/Service.svc" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>