<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:tns="http://tempuri.org/" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Service_Rcv_SAP_Rec" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xs:schema elementFormDefault="qualified" targetNamespace="http://tempuri.org/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:import namespace="http://schemas.datacontract.org/2004/07/" />
      <xs:element name="GetDataUsingDataContract">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q1="http://schemas.datacontract.org/2004/07/" minOccurs="0" name="composite" nillable="true" type="q1:SAP_Cols" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetDataUsingDataContractResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="GetDataUsingDataContractResult" nillable="true" type="xs:string" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:schema>
    <xs:schema xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/" attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:element name="anyType" nillable="true" type="xs:anyType" />
      <xs:element name="anyURI" nillable="true" type="xs:anyURI" />
      <xs:element name="base64Binary" nillable="true" type="xs:base64Binary" />
      <xs:element name="boolean" nillable="true" type="xs:boolean" />
      <xs:element name="byte" nillable="true" type="xs:byte" />
      <xs:element name="dateTime" nillable="true" type="xs:dateTime" />
      <xs:element name="decimal" nillable="true" type="xs:decimal" />
      <xs:element name="double" nillable="true" type="xs:double" />
      <xs:element name="float" nillable="true" type="xs:float" />
      <xs:element name="int" nillable="true" type="xs:int" />
      <xs:element name="long" nillable="true" type="xs:long" />
      <xs:element name="QName" nillable="true" type="xs:QName" />
      <xs:element name="short" nillable="true" type="xs:short" />
      <xs:element name="string" nillable="true" type="xs:string" />
      <xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte" />
      <xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt" />
      <xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong" />
      <xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort" />
      <xs:element name="char" nillable="true" type="tns:char" />
      <xs:simpleType name="char">
        <xs:restriction base="xs:int" />
      </xs:simpleType>
      <xs:element name="duration" nillable="true" type="tns:duration" />
      <xs:simpleType name="duration">
        <xs:restriction base="xs:duration">
          <xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?" />
          <xs:minInclusive value="-P10675199DT2H48M5.4775808S" />
          <xs:maxInclusive value="P10675199DT2H48M5.4775807S" />
        </xs:restriction>
      </xs:simpleType>
      <xs:element name="guid" nillable="true" type="tns:guid" />
      <xs:simpleType name="guid">
        <xs:restriction base="xs:string">
          <xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}" />
        </xs:restriction>
      </xs:simpleType>
      <xs:attribute name="FactoryType" type="xs:QName" />
      <xs:attribute name="Id" type="xs:ID" />
      <xs:attribute name="Ref" type="xs:IDREF" />
    </xs:schema>
    <xs:schema xmlns:tns="http://schemas.datacontract.org/2004/07/" elementFormDefault="qualified" targetNamespace="http://schemas.datacontract.org/2004/07/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:complexType name="SAP_Cols">
        <xs:sequence>
          <xs:element minOccurs="0" name="bank_name" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="bill_cycle" type="xs:int" />
          <xs:element minOccurs="0" name="bill_date" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="bill_number" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="bill_type" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="check_no" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="connected_pole_ini_number" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="consumption_kva" type="xs:float" />
          <xs:element minOccurs="0" name="consumption_kwah" type="xs:float" />
          <xs:element minOccurs="0" name="consumption_kwh" type="xs:float" />
          <xs:element minOccurs="0" name="contract_account_number" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cur_meter_reader_note" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="cur_meter_reading_date" type="xs:dateTime" />
          <xs:element minOccurs="0" name="cur_meter_reading_kva" type="xs:float" />
          <xs:element minOccurs="0" name="cur_meter_reading_kvah" type="xs:float" />
          <xs:element minOccurs="0" name="cur_meter_reading_kwh" type="xs:float" />
          <xs:element minOccurs="0" name="cur_meter_reading_time" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="demand_charges" type="xs:float" />
          <xs:element minOccurs="0" name="dssf" type="xs:float" />
          <xs:element minOccurs="0" name="dtupload" type="xs:dateTime" />
          <xs:element minOccurs="0" name="due_date" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="ed" type="xs:float" />
          <xs:element minOccurs="0" name="empid" type="xs:float" />
          <xs:element minOccurs="0" name="fixedcharges" type="xs:float" />
          <xs:element minOccurs="0" name="fuel_adjustment" type="xs:float" />
          <xs:element minOccurs="0" name="ifsc_code" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="inhouse_outsourced_sbm" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="installation" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="lpsc" type="xs:float" />
          <xs:element minOccurs="0" name="manufacturer_name" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="manufacturer_sr_no" type="xs:int" />
          <xs:element minOccurs="0" name="mcb_rent" type="xs:float" />
          <xs:element minOccurs="0" name="meter_number" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="meter_reader_name" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="meter_rent" type="xs:float" />
          <xs:element minOccurs="0" name="micrcode" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="miscellaneous_charges" type="xs:float" />
          <xs:element minOccurs="0" name="monthly_min_charges" type="xs:float" />
          <xs:element minOccurs="0" name="mr_doc_no" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="mru" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="neighbor_meter_no" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="no_of_days_billed" type="xs:int" />
          <xs:element minOccurs="0" name="octroi" type="xs:float" />
          <xs:element minOccurs="0" name="octroi_flag" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="payment_amount" type="xs:float" />
          <xs:element minOccurs="0" name="payment_date" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="payment_id" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="payment_mode" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="payment_remark" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="peakload_exemption_charges" type="xs:float" />
          <xs:element minOccurs="0" name="pf_incentive" type="xs:float" />
          <xs:element minOccurs="0" name="pf_surcharge" type="xs:float" />
          <xs:element minOccurs="0" name="prv_meter_reader_note" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="prv_meter_reading_date" type="xs:dateTime" />
          <xs:element minOccurs="0" name="prv_meter_reading_kva" type="xs:float" />
          <xs:element minOccurs="0" name="prv_meter_reading_kwah" type="xs:float" />
          <xs:element minOccurs="0" name="prv_meter_reading_kwh" type="xs:float" />
          <xs:element minOccurs="0" name="prv_meter_reading_time" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="sbm_number" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="scheduled_mrdate" type="xs:dateTime" />
          <xs:element minOccurs="0" name="service_charge" type="xs:float" />
          <xs:element minOccurs="0" name="service_rent" type="xs:float" />
          <xs:element minOccurs="0" name="sop" type="xs:float" />
          <xs:element minOccurs="0" name="street_name" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="sub_division_code" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="sundry_charges" type="xs:float" />
          <xs:element minOccurs="0" name="surcharge_leived" type="xs:float" />
          <xs:element minOccurs="0" name="synced" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="tot_amt_due_date" type="xs:float" />
          <xs:element minOccurs="0" name="tot_billamount" type="xs:float" />
          <xs:element minOccurs="0" name="tot_sop_ed_oct" type="xs:float" />
          <xs:element minOccurs="0" name="transfromercode" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="userid" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="voltage_surcharge" type="xs:float" />
        </xs:sequence>
      </xs:complexType>
      <xs:element name="SAP_Cols" nillable="true" type="tns:SAP_Cols" />
    </xs:schema>
  </wsdl:types>
  <wsdl:message name="IService_GetDataUsingDataContract_InputMessage">
    <wsdl:part name="parameters" element="tns:GetDataUsingDataContract" />
  </wsdl:message>
  <wsdl:message name="IService_GetDataUsingDataContract_OutputMessage">
    <wsdl:part name="parameters" element="tns:GetDataUsingDataContractResponse" />
  </wsdl:message>
  <wsdl:portType name="IService">
    <wsdl:operation name="GetDataUsingDataContract">
      <wsdl:input wsaw:Action="http://tempuri.org/IService/GetDataUsingDataContract" message="tns:IService_GetDataUsingDataContract_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IService/GetDataUsingDataContractResponse" message="tns:IService_GetDataUsingDataContract_OutputMessage" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BasicHttpBinding_IService" type="tns:IService">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="GetDataUsingDataContract">
      <soap:operation soapAction="http://tempuri.org/IService/GetDataUsingDataContract" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Service_Rcv_SAP_Rec">
    <wsdl:port name="BasicHttpBinding_IService" binding="tns:BasicHttpBinding_IService">
      <soap:address location="http://localhost:1298/WCFService_RcvSAPBill/Service.svc" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>